In [2]:
pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in .\AppData\Local\anaconda3\Lib\site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in .\AppData\Local\anaconda3\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in .\AppData\Local\anaconda3\Lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in .\AppData\Local\anaconda3\Lib\site-packages (from kagglehub) (4.68.2)
Requirement already satisfied: protobuf in .\AppData\Local\anaconda3\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (6.33.5)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\anaconda3\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Local\anaconda3\Lib\site-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\AppData\Local\anaconda3\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\AppData\Local\anaconda3\Lib\site-packages (from requests->kagglehub) (2026.6.17)
Requirement already satisfied: colorama in .\AppData\Local\anaconda3\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Installing collected packages: kagglesdk, kagglehub

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   ---------------------------------------- 2/2 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jaykay12/odi-cricket-matches-19712017")

print("Path to dataset files:", path)

Downloading to C:\Users\shivranjan.pathak\.cache\kagglehub\datasets\jaykay12\odi-cricket-matches-19712017\4.archive...

100%|██████████| 330k/330k [00:01<00:00, 290kB/s]

Extracting files...
Path to dataset files: C:\Users\shivranjan.pathak\.cache\kagglehub\datasets\jaykay12\odi-cricket-matches-19712017\versions\4

In [8]:
import os
 
for root, dirs, files in os.walk(path):
    for file in files:
        print(file)

CategoricalDataset.csv
ContinousDataset.csv
LabelledDataset.csv
originalDataset.csv

In [24]:
odi_categorical = pd.read_csv(os.path.join(path, "CategoricalDataset.csv"))

odi_continuous = pd.read_csv(os.path.join(path, "ContinousDataset.csv"))

In [25]:
print(odi_categorical.columns)

print(odi_continuous.columns)

Index(['Team 1_Afghanistan', 'Team 1_Australia', 'Team 1_Bangladesh',
       'Team 1_Bermuda', 'Team 1_Canada', 'Team 1_East Africa',
       'Team 1_England', 'Team 1_Hong Kong', 'Team 1_India', 'Team 1_Ireland',
       ...
       'Winner_New Zealand', 'Winner_P.N.G.', 'Winner_Pakistan',
       'Winner_Scotland', 'Winner_South Africa', 'Winner_Sri Lanka',
       'Winner_U.A.E.', 'Winner_U.S.A.', 'Winner_West Indies',
       'Winner_Zimbabwe'],
      dtype='str', length=240)
Index(['Unnamed: 0', 'Scorecard', 'Team 1', 'Team 2', 'Margin', 'Ground',
       'Match Date', 'Winner', 'Host_Country', 'Venue_Team1', 'Venue_Team2',
       'Innings_Team1', 'Innings_Team2'],
      dtype='str')

In [26]:
print(odi_categorical.head())

print(odi_categorical.tail())

print(odi_categorical.shape)

print(odi_categorical.info())

print(odi_categorical.describe(include="all"))

print(odi_categorical.sample(5))

print(odi_categorical.dtypes)

print(odi_categorical.columns)

print(odi_categorical.index)

print(odi_categorical.size)

   Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
0                   0                 1                  0               0
1                   0                 0                  0               0
2                   0                 0                  0               0
3                   0                 0                  0               0
4                   0                 0                  0               0

   Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
0              0                   0               0                 0
1              0                   0               1                 0
2              0                   0               1                 0
3              0                   0               1                 0
4              0                   0               0                 0

   Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
0             0               0  ...                   0              0
1             0               0  ...                   0              0
2             0               0  ...                   0              0
3             0               0  ...                   0              0
4             0               0  ...                   1              0

   Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
0                0                0                    0                 0
1                0                0                    0                 0
2                0                0                    0                 0
3                0                0                    0                 0
4                0                0                    0                 0

   Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
0              0              0                   0                0
1              0              0                   0                0
2              0              0                   0                0
3              0              0                   0                0
4              0              0                   0                0

[5 rows x 240 columns]
      Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
7489                   0                 0                  0               0
7490                   0                 0                  0               0
7491                   0                 0                  0               0
7492                   0                 0                  0               0
7493                   0                 0                  0               0

      Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
7489              0                   0               0                 0
7490              0                   0               0                 0
7491              0                   0               0                 0
7492              0                   0               0                 0
7493              0                   0               0                 0

      Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
7489             0               0  ...                   0              0
7490             0               0  ...                   0              0
7491             0               0  ...                   0              0
7492             0               0  ...                   0              0
7493             0               0  ...                   0              0

      Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
7489                0                0                    0                 0
7490                0                0                    0                 0
7491                0                0                    0                 0
7492                0                0                    0                 0
7493                0                0                    0                 0

      Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
7489              0              0                   0                0
7490              0              0                   0                0
7491              0              0                   0                0
7492              0              1                   0                0
7493              0              0                   0                0

[5 rows x 240 columns]
(7494, 240)
<class 'pandas.DataFrame'>
RangeIndex: 7494 entries, 0 to 7493
Columns: 240 entries, Team 1_Afghanistan to Winner_Zimbabwe
dtypes: int64(240)
memory usage: 13.7 MB
None
       Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  \
count         7494.000000       7494.000000        7494.000000
mean             0.010809          0.114625           0.043768
std              0.103408          0.318590           0.204593
min              0.000000          0.000000           0.000000
25%              0.000000          0.000000           0.000000
50%              0.000000          0.000000           0.000000
75%              0.000000          0.000000           0.000000
max              1.000000          1.000000           1.000000

       Team 1_Bermuda  Team 1_Canada  Team 1_East Africa  Team 1_England  \
count     7494.000000    7494.000000         7494.000000     7494.000000
mean         0.004804       0.010008            0.000534        0.088604
std          0.069148       0.099545            0.023099        0.284191
min          0.000000       0.000000            0.000000        0.000000
25%          0.000000       0.000000            0.000000        0.000000
50%          0.000000       0.000000            0.000000        0.000000
75%          0.000000       0.000000            0.000000        0.000000
max          1.000000       1.000000            1.000000        1.000000

       Team 1_Hong Kong  Team 1_India  Team 1_Ireland  ...  \
count       7494.000000   7494.000000     7494.000000  ...
mean           0.002402      0.117427        0.015079  ...
std            0.048954      0.321950        0.121874  ...
min            0.000000      0.000000        0.000000  ...
25%            0.000000      0.000000        0.000000  ...
50%            0.000000      0.000000        0.000000  ...
75%            0.000000      0.000000        0.000000  ...
max            1.000000      1.000000        1.000000  ...

       Winner_New Zealand  Winner_P.N.G.  Winner_Pakistan  Winner_Scotland  \
count         7494.000000    7494.000000      7494.000000      7494.000000
mean             0.086469       0.001334         0.124366         0.008273
std              0.281074       0.036508         0.330021         0.090587
min              0.000000       0.000000         0.000000         0.000000
25%              0.000000       0.000000         0.000000         0.000000
50%              0.000000       0.000000         0.000000         0.000000
75%              0.000000       0.000000         0.000000         0.000000
max              1.000000       1.000000         1.000000         1.000000

       Winner_South Africa  Winner_Sri Lanka  Winner_U.A.E.  Winner_U.S.A.  \
count          7494.000000       7494.000000    7494.000000    7494.000000
mean              0.096344          0.099013       0.002402       0.000267
std               0.295082          0.298699       0.048954       0.016335
min               0.000000          0.000000       0.000000       0.000000
25%               0.000000          0.000000       0.000000       0.000000
50%               0.000000          0.000000       0.000000       0.000000
75%               0.000000          0.000000       0.000000       0.000000
max               1.000000          1.000000       1.000000       1.000000

       Winner_West Indies  Winner_Zimbabwe
count         7494.000000      7494.000000
mean             0.101414         0.034428
std              0.301897         0.182337
min              0.000000         0.000000
25%              0.000000         0.000000
50%              0.000000         0.000000
75%              0.000000         0.000000
max              1.000000         1.000000

[8 rows x 240 columns]
      Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
4520                   0                 0                  0               0
2136                   0                 0                  0               0
3738                   0                 0                  0               0
2383                   0                 0                  0               0
7152                   0                 0                  0               0

      Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
4520              0                   0               0                 0
2136              0                   0               0                 0
3738              0                   0               0                 0
2383              0                   0               0                 0
7152              0                   0               0                 0

      Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
4520             0               0  ...                   0              0
2136             0               0  ...                   0              0
3738             0               0  ...                   0              0
2383             0               0  ...                   0              0
7152             0               0  ...                   1              0

      Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
4520                0                0                    0                 0
2136                0                0                    1                 0
3738                1                0                    0                 0
2383                0                0                    0                 0
7152                0                0                    0                 0

      Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
4520              0              0                   1                0
2136              0              0                   0                0
3738              0              0                   0                0
2383              0              0                   0                0
7152              0              0                   0                0

[5 rows x 240 columns]
Team 1_Afghanistan    int64
Team 1_Australia      int64
Team 1_Bangladesh     int64
Team 1_Bermuda        int64
Team 1_Canada         int64
                      ...
Winner_Sri Lanka      int64
Winner_U.A.E.         int64
Winner_U.S.A.         int64
Winner_West Indies    int64
Winner_Zimbabwe       int64
Length: 240, dtype: object
Index(['Team 1_Afghanistan', 'Team 1_Australia', 'Team 1_Bangladesh',
       'Team 1_Bermuda', 'Team 1_Canada', 'Team 1_East Africa',
       'Team 1_England', 'Team 1_Hong Kong', 'Team 1_India', 'Team 1_Ireland',
       ...
       'Winner_New Zealand', 'Winner_P.N.G.', 'Winner_Pakistan',
       'Winner_Scotland', 'Winner_South Africa', 'Winner_Sri Lanka',
       'Winner_U.A.E.', 'Winner_U.S.A.', 'Winner_West Indies',
       'Winner_Zimbabwe'],
      dtype='str', length=240)
RangeIndex(start=0, stop=7494, step=1)
1798560

In [27]:
print(odi_categorical.isnull().sum())

print(odi_categorical.isna().sum())

print(odi_categorical.notna().sum())

print(odi_categorical.dropna())

print(odi_categorical.fillna("Unknown"))

print(odi_categorical.ffill())

print(odi_categorical.bfill())

Team 1_Afghanistan    0
Team 1_Australia      0
Team 1_Bangladesh     0
Team 1_Bermuda        0
Team 1_Canada         0
                     ..
Winner_Sri Lanka      0
Winner_U.A.E.         0
Winner_U.S.A.         0
Winner_West Indies    0
Winner_Zimbabwe       0
Length: 240, dtype: int64
Team 1_Afghanistan    0
Team 1_Australia      0
Team 1_Bangladesh     0
Team 1_Bermuda        0
Team 1_Canada         0
                     ..
Winner_Sri Lanka      0
Winner_U.A.E.         0
Winner_U.S.A.         0
Winner_West Indies    0
Winner_Zimbabwe       0
Length: 240, dtype: int64
Team 1_Afghanistan    7494
Team 1_Australia      7494
Team 1_Bangladesh     7494
Team 1_Bermuda        7494
Team 1_Canada         7494
                      ...
Winner_Sri Lanka      7494
Winner_U.A.E.         7494
Winner_U.S.A.         7494
Winner_West Indies    7494
Winner_Zimbabwe       7494
Length: 240, dtype: int64
      Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
0                      0                 1                  0               0
1                      0                 0                  0               0
2                      0                 0                  0               0
3                      0                 0                  0               0
4                      0                 0                  0               0
...                  ...               ...                ...             ...
7489                   0                 0                  0               0
7490                   0                 0                  0               0
7491                   0                 0                  0               0
7492                   0                 0                  0               0
7493                   0                 0                  0               0

      Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
0                 0                   0               0                 0
1                 0                   0               1                 0
2                 0                   0               1                 0
3                 0                   0               1                 0
4                 0                   0               0                 0
...             ...                 ...             ...               ...
7489              0                   0               0                 0
7490              0                   0               0                 0
7491              0                   0               0                 0
7492              0                   0               0                 0
7493              0                   0               0                 0

      Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
0                0               0  ...                   0              0
1                0               0  ...                   0              0
2                0               0  ...                   0              0
3                0               0  ...                   0              0
4                0               0  ...                   1              0
...            ...             ...  ...                 ...            ...
7489             0               0  ...                   0              0
7490             0               0  ...                   0              0
7491             0               0  ...                   0              0
7492             0               0  ...                   0              0
7493             0               0  ...                   0              0

      Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
0                   0                0                    0                 0
1                   0                0                    0                 0
2                   0                0                    0                 0
3                   0                0                    0                 0
4                   0                0                    0                 0
...               ...              ...                  ...               ...
7489                0                0                    0                 0
7490                0                0                    0                 0
7491                0                0                    0                 0
7492                0                0                    0                 0
7493                0                0                    0                 0

      Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
0                 0              0                   0                0
1                 0              0                   0                0
2                 0              0                   0                0
3                 0              0                   0                0
4                 0              0                   0                0
...             ...            ...                 ...              ...
7489              0              0                   0                0
7490              0              0                   0                0
7491              0              0                   0                0
7492              0              1                   0                0
7493              0              0                   0                0

[7494 rows x 240 columns]
      Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
0                      0                 1                  0               0
1                      0                 0                  0               0
2                      0                 0                  0               0
3                      0                 0                  0               0
4                      0                 0                  0               0
...                  ...               ...                ...             ...
7489                   0                 0                  0               0
7490                   0                 0                  0               0
7491                   0                 0                  0               0
7492                   0                 0                  0               0
7493                   0                 0                  0               0

      Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
0                 0                   0               0                 0
1                 0                   0               1                 0
2                 0                   0               1                 0
3                 0                   0               1                 0
4                 0                   0               0                 0
...             ...                 ...             ...               ...
7489              0                   0               0                 0
7490              0                   0               0                 0
7491              0                   0               0                 0
7492              0                   0               0                 0
7493              0                   0               0                 0

      Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
0                0               0  ...                   0              0
1                0               0  ...                   0              0
2                0               0  ...                   0              0
3                0               0  ...                   0              0
4                0               0  ...                   1              0
...            ...             ...  ...                 ...            ...
7489             0               0  ...                   0              0
7490             0               0  ...                   0              0
7491             0               0  ...                   0              0
7492             0               0  ...                   0              0
7493             0               0  ...                   0              0

      Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
0                   0                0                    0                 0
1                   0                0                    0                 0
2                   0                0                    0                 0
3                   0                0                    0                 0
4                   0                0                    0                 0
...               ...              ...                  ...               ...
7489                0                0                    0                 0
7490                0                0                    0                 0
7491                0                0                    0                 0
7492                0                0                    0                 0
7493                0                0                    0                 0

      Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
0                 0              0                   0                0
1                 0              0                   0                0
2                 0              0                   0                0
3                 0              0                   0                0
4                 0              0                   0                0
...             ...            ...                 ...              ...
7489              0              0                   0                0
7490              0              0                   0                0
7491              0              0                   0                0
7492              0              1                   0                0
7493              0              0                   0                0

[7494 rows x 240 columns]
      Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
0                      0                 1                  0               0
1                      0                 0                  0               0
2                      0                 0                  0               0
3                      0                 0                  0               0
4                      0                 0                  0               0
...                  ...               ...                ...             ...
7489                   0                 0                  0               0
7490                   0                 0                  0               0
7491                   0                 0                  0               0
7492                   0                 0                  0               0
7493                   0                 0                  0               0

      Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
0                 0                   0               0                 0
1                 0                   0               1                 0
2                 0                   0               1                 0
3                 0                   0               1                 0
4                 0                   0               0                 0
...             ...                 ...             ...               ...
7489              0                   0               0                 0
7490              0                   0               0                 0
7491              0                   0               0                 0
7492              0                   0               0                 0
7493              0                   0               0                 0

      Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
0                0               0  ...                   0              0
1                0               0  ...                   0              0
2                0               0  ...                   0              0
3                0               0  ...                   0              0
4                0               0  ...                   1              0
...            ...             ...  ...                 ...            ...
7489             0               0  ...                   0              0
7490             0               0  ...                   0              0
7491             0               0  ...                   0              0
7492             0               0  ...                   0              0
7493             0               0  ...                   0              0

      Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
0                   0                0                    0                 0
1                   0                0                    0                 0
2                   0                0                    0                 0
3                   0                0                    0                 0
4                   0                0                    0                 0
...               ...              ...                  ...               ...
7489                0                0                    0                 0
7490                0                0                    0                 0
7491                0                0                    0                 0
7492                0                0                    0                 0
7493                0                0                    0                 0

      Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
0                 0              0                   0                0
1                 0              0                   0                0
2                 0              0                   0                0
3                 0              0                   0                0
4                 0              0                   0                0
...             ...            ...                 ...              ...
7489              0              0                   0                0
7490              0              0                   0                0
7491              0              0                   0                0
7492              0              1                   0                0
7493              0              0                   0                0

[7494 rows x 240 columns]
      Team 1_Afghanistan  Team 1_Australia  Team 1_Bangladesh  Team 1_Bermuda  \
0                      0                 1                  0               0
1                      0                 0                  0               0
2                      0                 0                  0               0
3                      0                 0                  0               0
4                      0                 0                  0               0
...                  ...               ...                ...             ...
7489                   0                 0                  0               0
7490                   0                 0                  0               0
7491                   0                 0                  0               0
7492                   0                 0                  0               0
7493                   0                 0                  0               0

      Team 1_Canada  Team 1_East Africa  Team 1_England  Team 1_Hong Kong  \
0                 0                   0               0                 0
1                 0                   0               1                 0
2                 0                   0               1                 0
3                 0                   0               1                 0
4                 0                   0               0                 0
...             ...                 ...             ...               ...
7489              0                   0               0                 0
7490              0                   0               0                 0
7491              0                   0               0                 0
7492              0                   0               0                 0
7493              0                   0               0                 0

      Team 1_India  Team 1_Ireland  ...  Winner_New Zealand  Winner_P.N.G.  \
0                0               0  ...                   0              0
1                0               0  ...                   0              0
2                0               0  ...                   0              0
3                0               0  ...                   0              0
4                0               0  ...                   1              0
...            ...             ...  ...                 ...            ...
7489             0               0  ...                   0              0
7490             0               0  ...                   0              0
7491             0               0  ...                   0              0
7492             0               0  ...                   0              0
7493             0               0  ...                   0              0

      Winner_Pakistan  Winner_Scotland  Winner_South Africa  Winner_Sri Lanka  \
0                   0                0                    0                 0
1                   0                0                    0                 0
2                   0                0                    0                 0
3                   0                0                    0                 0
4                   0                0                    0                 0
...               ...              ...                  ...               ...
7489                0                0                    0                 0
7490                0                0                    0                 0
7491                0                0                    0                 0
7492                0                0                    0                 0
7493                0                0                    0                 0

      Winner_U.A.E.  Winner_U.S.A.  Winner_West Indies  Winner_Zimbabwe
0                 0              0                   0                0
1                 0              0                   0                0
2                 0              0                   0                0
3                 0              0                   0                0
4                 0              0                   0                0
...             ...            ...                 ...              ...
7489              0              0                   0                0
7490              0              0                   0                0
7491              0              0                   0                0
7492              0              1                   0                0
7493              0              0                   0                0

[7494 rows x 240 columns]

In [28]:
# Number of rows
len(odi_categorical)

# Number of columns
len(odi_categorical.columns)

# First row
odi_categorical.iloc[0]

# Last row
odi_categorical.iloc[-1]

# First column
odi_categorical.iloc[:, 0]

# Last column
odi_categorical.iloc[:, -1]

# First 3 columns
odi_categorical.iloc[:, :3]

# Last 3 columns
odi_categorical.iloc[:, -3:]

# First 20 rows
odi_categorical.iloc[:20]

# Row 10 to 20
odi_categorical.iloc[10:21]

# Random row
odi_categorical.sample()

# Random 10 rows
odi_categorical.sample(10)

# Count non-null values
odi_categorical.count()

# Check if dataset has null values
odi_categorical.isnull().any()

# Total null values
odi_categorical.isnull().sum().sum()

# Fill null values
odi_categorical.fillna("NA")

# Remove rows with null values
odi_categorical.dropna()

# Remove columns with null values
odi_categorical.dropna(axis=1)

# Transpose dataset
odi_categorical.T

# Copy dataset
new_df = odi_categorical.copy()

# Reverse row order
odi_categorical[::-1]

# Column names as list
odi_categorical.columns.tolist()

# Index values
odi_categorical.index.tolist()

# Check duplicate rows
odi_categorical.duplicated()

# Remove duplicate rows
odi_categorical.drop_duplicates()

# Count unique values in each column
odi_categorical.nunique()

# Display unique values of first column
odi_categorical.iloc[:, 0].unique()

# Frequency count
odi_categorical.iloc[:, 0].value_counts()

Team 1_Afghanistan
0    7413
1      81
Name: count, dtype: int64

In [39]:
odi_categorical.isnull().sum()

odi_categorical.isnull().any()

odi_categorical.notnull().sum()

odi_categorical.fillna("Unknown")

odi_categorical.dropna()

,Team 1_Afghanistan,Team 1_Australia,Team 1_Bangladesh,Team 1_Bermuda,Team 1_Canada,Team 1_East Africa,Team 1_England,Team 1_Hong Kong,Team 1_India,Team 1_Ireland,...,Winner_New Zealand,Winner_P.N.G.,Winner_Pakistan,Winner_Scotland,Winner_South Africa,Winner_Sri Lanka,Winner_U.A.E.,Winner_U.S.A.,Winner_West Indies,Winner_Zimbabwe
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7493,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [40]:
odi_categorical.duplicated().sum()

odi_categorical.drop_duplicates()

,Team 1_Afghanistan,Team 1_Australia,Team 1_Bangladesh,Team 1_Bermuda,Team 1_Canada,Team 1_East Africa,Team 1_England,Team 1_Hong Kong,Team 1_India,Team 1_Ireland,...,Winner_New Zealand,Winner_P.N.G.,Winner_Pakistan,Winner_Scotland,Winner_South Africa,Winner_Sri Lanka,Winner_U.A.E.,Winner_U.S.A.,Winner_West Indies,Winner_Zimbabwe
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7487,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7493,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
odi_categorical.sort_index()

odi_categorical.sort_index(ascending=False)

odi_categorical.sort_values(
    by=odi_categorical.columns[0]
)

odi_categorical.sort_values(
    by=odi_categorical.columns[0],
    ascending=False
)

,Team 1_Afghanistan,Team 1_Australia,Team 1_Bangladesh,Team 1_Bermuda,Team 1_Canada,Team 1_East Africa,Team 1_England,Team 1_Hong Kong,Team 1_India,Team 1_Ireland,...,Winner_New Zealand,Winner_P.N.G.,Winner_Pakistan,Winner_Scotland,Winner_South Africa,Winner_Sri Lanka,Winner_U.A.E.,Winner_U.S.A.,Winner_West Indies,Winner_Zimbabwe
3539,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3308,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3186,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3187,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3403,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7493,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
odi_continuous.mean(numeric_only=True)

odi_continuous.median(numeric_only=True)

odi_continuous.max(numeric_only=True)

odi_continuous.min(numeric_only=True)

odi_continuous.sum(numeric_only=True)

odi_continuous.std(numeric_only=True)

odi_continuous.var(numeric_only=True)

odi_continuous.count()

odi_continuous.corr(numeric_only=True)

            Unnamed: 0
Unnamed: 0         1.0

In [44]:
# Add column
odi_categorical["ID"] = range(
    1,
    len(odi_categorical)+1
)

# Display
odi_categorical.head()

# Remove column
odi_categorical.drop(
    "ID",
    axis=1,
    inplace=True
)

C:\Users\shivranjan.pathak\AppData\Local\Temp\ipykernel_13652\2551856865.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  odi_categorical["ID"] = range(